-- Comptes joueurs (Phase 3, section 6) : chaque joueur a désormais un nom
-- unique et un mot de passe haché (argon2, jamais stocké en clair), et les
-- requêtes /save passent par un jeton de session au lieu de l'id 1 codé en
-- dur. Base locale = données de test jetables (décision projet) : on repart
-- de zéro plutôt que de migrer l'unique ligne existante.
DELETE FROM player_characters;
DELETE FROM battle_history;
DELETE FROM inventory_items;
DELETE FROM saves;
DELETE FROM players;

ALTER TABLE players ADD COLUMN password_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE players ALTER COLUMN password_hash DROP DEFAULT;
ALTER TABLE players ADD CONSTRAINT players_name_unique UNIQUE (name);

-- saves.id devient auto-généré (avant : toujours 1 en dur) ; player_id
-- devient la clé de recherche pour /save, avec une contrainte d'unicité
-- pour permettre l'upsert ON CONFLICT (player_id).
ALTER TABLE saves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE saves ALTER COLUMN player_id DROP DEFAULT;
ALTER TABLE saves ADD CONSTRAINT saves_player_id_unique UNIQUE (player_id);

CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
